print("axel")
print("18")
print("faint")
print(146 + 134)
print("probando imprimir texto en python")
print("probando guardarlo")
print("no consigo guardarlo")
print("hola holaaaa")
print("lo solucioneee, tiene que mostrar la m de cambios ")