print("axel")
print("18")
print("faint")
print(146 + 134)
print("probando imprimir texto en python")
print("probando guardarlo")
print("no consigo guardarlo")
print("hola holaaaa")
print("lo solucioneee, tiene que mostrar la m de cambios ")
print("tiene que salir save all, guardar todo, al lado de open editors")
print("5")
print("4")
print("3")
print("2")
print("1")

#escribire el nombre de mi cancion favorita
print("faint")
print(".-.")
#ahora la letra de mi cancion
print("chaparrita")
print("ella no sigue la moda")
print("le gusta bailar sola")
print("conmigo tu eres abusadora")
print("dejame ser quien te explora")
print("que yo quiero hacerte cosiiiitas")
print("chaparrita boniiita")
print("te voy a comer cereciiita")
print("bellaca y dulcecitaa")
print()